### ISSUE TITLE
Help Request - Setting up Alsa Device

### ISSUE THREAD

**Issue by cdlenfert** [owntone/forked-daapd#1192]
I've worked through the [README_ALSA.md](https://github.com/ejurgensen/forked-daapd/blob/master/README_ALSA.md) instructions a few times now. I'm able to get sound output, however I'm never able to get sound output when the volume setting is below 25%. I'd like the full range of the volume slider (other than when it's totally at 0) to output some sound.

**From the Readme and my config here is what I'm doing:**

What I had in my config (provided limited volume range)
```
# Local audio output
audio {
	# Name - used in the speaker list in Remote
	nickname = "PogoPlug"

	# Type of the output (alsa, pulseaudio, dummy or disabled)
	type = "alsa"

	# Audio PCM device name for local audio output - ALSA only
#	card = "plughw:Device"

	# Mixer channel to use for volume control - ALSA only
	# If not set, PCM will be used if available, otherwise Master.
	mixer = "Speaker"

}
```

My results from `aplay` commands and `forked-daapd.log` set to INFO

```
root@debian:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```
So I expected my device is `hw:1,0`

```
root@debian:~# aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
sysdefault:CARD=Device
    USB Audio Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Front speakers
surround21:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Direct sample mixing device
dsnoop:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Direct sample snooping device
hw:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Direct hardware device without any conversions
plughw:CARD=Device,DEV=0
    USB Audio Device, USB Audio
    Hardware device with all software conversions
```

To get mixer info only for card 1

```
root@debian:~# amixer -c 1
Simple mixer control 'Speaker',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 37
  Mono:
  Front Left: Playback 13 [35%] [-24.00dB] [on]
  Front Right: Playback 13 [35%] [-24.00dB] [on]
Simple mixer control 'Mic',0
  Capabilities: pvolume pvolume-joined cvolume cvolume-joined pswitch pswitch-joined cswitch cswitch-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: Playback 0 - 31 Capture 0 - 35
  Mono: Playback 16 [52%] [-7.00dB] [off] Capture 20 [57%] [8.00dB] [on]
Simple mixer control 'Auto Gain Control',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
```
Seems like I pretty obviously want the mixer device of `Speaker`

I made the following config changes:

```
# Local audio output
audio {
        # Name - used in the speaker list in Remote
        nickname = "PogoPlug"

        # Type of the output (alsa, pulseaudio, dummy or disabled)
        type = "alsa"

        # Audio PCM device name for local audio output - ALSA only
        card = "hw:1,0”

        # Mixer channel to use for volume control - ALSA only
        # If not set, PCM will be used if available, otherwise Master.
        mixer = "Speaker"

}
```
This resulted in no audio at all and the following feedback from `forked-daapd.log`

```
[2021-02-12 10:16:36] [ WARN]   laudio: Failed to probe ALSA card=0 - No such file or directory
[2021-02-12 10:16:36] [ INFO]   laudio: Available ALSA playback mixer(s) on hw:1 CARD=Device (USB Audio Device): 'Speaker' 'Mic'
[2021-02-12 10:16:36] [ INFO]   laudio: Adding ALSA device 'hw:1,0' with name 'PogoPlug'
```
So I changed the config to card = `hw:Device`

Log output is very similar, except this time I have audio above 25%
```
[2021-02-12 10:28:52] [ WARN]   laudio: Failed to probe ALSA card=0 - No such file or directory
[2021-02-12 10:28:52] [ INFO]   laudio: Available ALSA playback mixer(s) on hw:1 CARD=Device (USB Audio Device): 'Speaker' 'Mic'
[2021-02-12 10:28:52] [ INFO]   laudio: Adding ALSA device 'hw:Device' with name 'PogoPlug'
```
Is it possible the issue is with my `/etc/asound.conf config`

```
root@debian:~# cat /etc/asound.conf 
pcm.!default {
    type hw
    card 1
}

ctl.!default {
    type hw           
    card 1
}

```
This hasn't always been an issue with this USB DAC and Forked-Daapd, and I understand that FD may have nothing to do with the issue. I've since replaced my rootfs drive and upgraded to Debian Buster and made countless FD upgrades. Appreciate any ideas or nudges in the right direction.

**Comment by cdlenfert** [comment]
Update: A bit more info. I can confirm that when I use Alsamixer to control volume levels, the same behavior happens. As soon as I change the volume to 24% it jumps straight to 0%. I'm only using Alsa, not Pulseaudio or anything else that I know of.

**Comment by whatdoineed2do** [comment]
Yes the logic in FD for volume setting is EXACTLY the same as alsamixer as that's where I borrowed the code :). The prev vol adjustment was something that didn't match human expectation

To your problem is remember the Alamixer code has a cutoff point where it decides if it's below this value for the sound device then it's basically inaudible and it'll just set to 0.  This is probably what's happening here

**Comment by cdlenfert** [comment]
> Yes the logic in FD for volume setting is EXACTLY the same as alsamixer as that's where I borrowed the code :). The prev vol adjustment was something that didn't match human expectation
> 
> To your problem is remember the Alamixer code has a cutoff point where it decides if it's below this value for the sound device then it's basically inaudible and it'll just set to 0. This is probably what's happening here

@whatdoineed2do Thank you for your response. It all makes sense to me, but I can't seem to find anything pointing me toward a solution that would allow a more natural use of the volume slider (in Alsamixer or FD). Have you ever come across this issue yourself? Are you aware of any workarounds?

**Comment by whatdoineed2do** [comment]
Unfortuantely, i dont know if there is a fix for this.  The code segment (from alsamixer an in FD) that relate to this is:

https://github.com/ejurgensen/forked-daapd/blob/76c52bba3b049d11f210751ab18331965cb78b61/src/outputs/alsa.c#L302-L371

Note the comment and the check `se_linear_dB_scale()` to - it uses a threshold to determine how it set the volume.  It would be useful to debug in there to see how its working - the strange behaviour may very well just be how the driver of your USB dac is handling this but I'm speculating.
