### ISSUE TITLE
You can find Xiaoai speaker in swilsonau / docker airconnect on your mobile phone, but you can't find Xiaoai speaker in daapd

### ISSUE THREAD

**Issue by hasspi88** [owntone/forked-daapd#1205]
You can find Xiaoai speaker in swilsonau / docker airconnect [on](url) your mobile phone, but you can't find Xiaoai speaker in daapd
![114](https://user-images.githubusercontent.com/77336160/110581052-c7b3c880-81a4-11eb-830f-7c691065a2de.png)
![115](https://user-images.githubusercontent.com/77336160/110581058-cb474f80-81a4-11eb-8910-96df76b530f6.jpg)
![Uploading 115.jpg…]()

**Comment by ejurgensen** [comment]
Please set the log level to debug (in /etc/forked-daapd.conf) and try to get some logging of when the error happens. Don’t cut and paste lengthy log outtakes here on github. Instead, attach the log file.

**Comment by ejurgensen** [comment]
Closing, no feedback
