### ISSUE TITLE
Airplay speakers not showing up

### ISSUE THREAD

**Issue by stefan1983** [owntone/forked-daapd#1207]
Hi, I am using two Sonos Play 5 (1st gen) speakers and also the docker image "airconnect" to be able to use them as airplay speakers as well. The speakers work well as airplay speakers for my iPhone, my iMac and also my MacbookPro (Apple Music, Podcasts, normal audio output....). Only the forked-daapd server is not able to see the speakers. Is there anything I could do to add them?

<img width="392" alt="image" src="https://user-images.githubusercontent.com/8542806/111010573-39536880-8397-11eb-85a0-84260522643f.png">
 
**Küche+
Schlafzimmer+**
Both are the mentioned Sonos speakers

Some time ago I tried out the HomePod mini and this showed up right away.
I would like to use the iOS Remote App to manage the forked-daapd server and play music on selected airplay devices.

Thanks

PS: forked-daapd VERSION 27.2 on debian linux (running as a docker image)

**Comment by stefan1983** [comment]
Is it probably because of the airplay device name containing a "+"?

**Comment by ejurgensen** [comment]
Perhaps the Sonos are only Airplay 2, and if that docker version is the actual 27.2 release then it wouldn't have support for that.

You can check what is announced with `avahi-browse -a -k`. If the speakers don't show _raop._tcp then that's the likely cause.

**Comment by ejurgensen** [comment]
Closing, no feedback
