### ISSUE TITLE
connect Windows virtual network sound card to forked-daapd for Airplay

### ISSUE THREAD

**Issue by jpmorrison** [owntone/forked-daapd#1208]
I have forked-daapd working with AppleTV - so far so good!

scream is a virtual sound card for Windows - it has Windows, Android and Unix clients 
https://github.com/duncanthrax/scream

I installed scream in Windows 10, reconfigured audio for 16 bit - it defaults to 32 bit which daapd doesn't like.
I installed the scream receiver in Ubuntu. It's using raw output to a fifo and daapd is playing on my AppleTV.
Except for iTunes, Windows apps can't play to Airplay devices.  Should work for Chromecast too.

I'd like to get this working with cpiped - there's some sound quality issues with raw/stdio.
scream receiver supports alsa so maybe there's a way to setup a virtual sound card that cpiped can use?

**Comment by jpmorrison** [comment]
I don’t have a sound card on the server so this was really easy:

sudo modprobe snd-aloop

scream -o alsa -i eth0 &
cpiped AUX &


Sound quality is great now.

**Comment by ejurgensen** [comment]
Thanks for sharing the solution to your issue. I will close it.
