### ISSUE TITLE
Bad request (play, queue, title)

### ISSUE THREAD

**Issue by boehser-enkel** [owntone/forked-daapd#1216]
Hi,

cant control it via url:

http://192.168.88.200:3689/api/queue/items/add?uris=library:artist:643928888069427056

http://192.168.88.200:3689/api/player/play

-> 500 Bad request

Status:

> homebridge@raspberrypi:~ $ systemctl status forked-daapd
● forked-daapd.service - DAAP/DACP (iTunes) and MPD server, supporting AirPlay and Spotify
   Loaded: loaded (/lib/systemd/system/forked-daapd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-03-31 08:38:38 CEST; 10min ago
     Docs: man:forked-daapd(8)
 Main PID: 20814 (forked-daapd)
    Tasks: 13 (limit: 4915)
   CGroup: /system.slice/forked-daapd.service
           └─20814 /usr/sbin/forked-daapd -f

> Mar 31 08:38:38 raspberrypi forked-daapd[20814]: [2021-03-31 08:38:38] [  LOG]       db: Configured to use database file '/var/cache/forked-daapd/songs3.db'
> Mar 31 08:38:38 raspberrypi forked-daapd[20814]: [2021-03-31 08:38:38] [  LOG]       db: Now vacuuming database, this may take some time...
> Mar 31 08:38:39 raspberrypi forked-daapd[20814]: [2021-03-31 08:38:39] [  LOG]       db: Database OK with 1 active files and 6 active playlists
> Mar 31 08:38:39 raspberrypi forked-daapd[20814]: [2021-03-31 08:38:39] [  LOG]   laudio: Pulseaudio failed with error: Connection refused
> Mar 31 08:38:39 raspberrypi forked-daapd[20814]: [2021-03-31 08:38:39] [  LOG]   laudio: Error initializing Pulseaudio: Connection refused
> Mar 31 08:38:39 raspberrypi forked-daapd[20814]: [2021-03-31 08:38:39] [  LOG]     scan: Bulk library scan completed in 0 sec
> Mar 31 08:38:39 raspberrypi forked-daapd[20814]: [2021-03-31 08:38:39] [  LOG]      lib: Library init scan completed in 0 sec (0 changes)
> Mar 31 08:39:37 raspberrypi forked-daapd[20814]: [2021-03-31 08:39:37] [  LOG]      web: Unrecognized path '/api/queue/items/add' in JSON api request: '/api/queue/items/add?uris=library:artist:643928888069427
> Mar 31 08:39:47 raspberrypi forked-daapd[20814]: [2021-03-31 08:39:47] [  LOG]      web: Unrecognized path '/api/player/play' in JSON api request: '/api/player/play'
> Mar 31 08:48:19 raspberrypi forked-daapd[20814]: [2021-03-31 08:48:19] [  LOG]      web: Unrecognized path '/api/queue/clear' in JSON api request: '/api/queue/clear'
> 
>

**Comment by ejurgensen** [comment]
Looks to me like you might not be using the correct HTTP method? These should be PUT requests.

**Comment by boehser-enkel** [comment]
Yes that‘s it. Browser uses GET
