### ISSUE TITLE
Request failed status: 500 Internal Server Error

### ISSUE THREAD

**Issue by paskovitch** [owntone/forked-daapd#1217]
Hi! I have a homepod mini and forked-daap worked fine.
From day to day I get the following error message if I want to select homepod as output:
Request failed (status: 500 Internal Server Error, url: http://192.168.0.172:3689/api/outputs/97664486601308/toggle)
I use RPi4 to run forked-daapd.
What could be the problem?

**Comment by ejurgensen** [comment]
I can't say based on this info alone

**Comment by ejurgensen** [comment]
Please set the log level to debug (in /etc/forked-daapd.conf) and try to get some logging of when the error happens. Don’t cut and paste lengthy log outtakes here on github. Instead, attach the log file.

**Comment by paskovitch** [comment]
[forked-daapd.log](https://github.com/owntone/forked-daapd/files/6239072/forked-daapd.log)
Here is the log file.

**Comment by ejurgensen** [comment]
The log level is not set to debug when the issue occurs, but even with normal log level the issue seems to be that the device requires PIN or password.

**Comment by paskovitch** [comment]
[forked-daapd.log](https://github.com/owntone/forked-daapd/files/6239146/forked-daapd.log)
Sorry. Here is the debug mode log file. How can I add  PIN or password to Homepod Mini? I have to reset the Homepod Mini?
![web](https://user-images.githubusercontent.com/44291654/113203973-fcc7ae00-926c-11eb-9206-5189a3ec040b.png)
I can't pair on the forked-daapd web page.

**Comment by paskovitch** [comment]
I found the solution. I had a bad airplay setting, password protection was on. Thanks for your help!
